name: Deploy (staging)
on:
  push:
    branches:
      - main
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'chancedigital/slim-chance'
    steps:

      # Setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read Node version
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Set Node version
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      # Install deps with cache
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.3
          version: 1
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache-dir-path.outputs.cache-hit != 'true'
        run: yarn
      - name: Run build
        run: yarn build

      # Deploy to staging
      - name: Deploy to staging
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'slimandhuskys'
          server: ${{ secrets.SFTP_SERVER }}
          ssh_private_key: ${{ secrets.SSH_SECRET }}
          local_path: './*'
          remote_path: '/www/slimandhuskys_612/public/wp-content/themes/slim-chance'
          args: '-o ConnectTimeout=5'
